namespace Reddit.MetaData
{
    public class ChildData
    {
        public object Approved_at_utc { get; set; }
        public string Subreddit { get; set; }
        public string Selftext { get; set; }
        public string Author_fullname { get; set; }
        public bool Saved { get; set; }
        public object Mod_reason_title { get; set; }
        public int Gilded { get; set; }
        public bool Clicked { get; set; }
        public string Title { get; set; }
        public object[] Link_flair_richtext { get; set; }
        public string Subreddit_name_prefixed { get; set; }
        public bool Hidden { get; set; }
        public int? Pwls { get; set; }
        public string Link_flair_css_class { get; set; }
        public int Downs { get; set; }
        public int? Thumbnail_height { get; set; }
        public object Top_awarded_type { get; set; }
        public bool Hide_score { get; set; }
        public string Name { get; set; }
        public bool Quarantine { get; set; }
        public string Link_flair_text_color { get; set; }
        public float Upvote_ratio { get; set; }
        public string Author_flair_background_color { get; set; }
        public string Subreddit_type { get; set; }
        public int Ups { get; set; }
        public int Total_awards_received { get; set; }
        public Media_Embed Media_embed { get; set; }
        public int? Thumbnail_width { get; set; }
        public string Author_flair_template_id { get; set; }
        public bool Is_original_content { get; set; }
        public object[] User_reports { get; set; }
        public object Secure_media { get; set; }
        public bool Is_reddit_media_domain { get; set; }
        public bool Is_meta { get; set; }
        public object Category { get; set; }
        public Secure_Media_Embed Secure_media_embed { get; set; }
        public string Link_flair_text { get; set; }
        public bool Can_mod_post { get; set; }
        public int Score { get; set; }
        public object Approved_by { get; set; }
        public bool Author_premium { get; set; }
        public string Thumbnail { get; set; }
        public bool Edited { get; set; }
        public string Author_flair_css_class { get; set; }
        public object[] Author_flair_richtext { get; set; }
        public Gildings Gildings { get; set; }
        public string[] Content_categories { get; set; }
        public bool Is_self { get; set; }
        public object Mod_note { get; set; }
        public float Created { get; set; }
        public string Link_flair_type { get; set; }
        public int? Wls { get; set; }
        public object Removed_by_category { get; set; }
        public object Banned_by { get; set; }
        public string Author_flair_type { get; set; }
        public string Domain { get; set; }
        public bool Allow_live_comments { get; set; }
        public string Selftext_html { get; set; }
        public object Likes { get; set; }
        public string Suggested_sort { get; set; }
        public object Banned_at_utc { get; set; }
        public object View_count { get; set; }
        public bool Archived { get; set; }
        public bool No_follow { get; set; }
        public bool Is_crosspostable { get; set; }
        public bool Pinned { get; set; }
        public bool Over_18 { get; set; }
        public All_Awardings[] All_awardings { get; set; }
        public object[] Awarders { get; set; }
        public bool Media_only { get; set; }
        public bool Can_gild { get; set; }
        public bool Spoiler { get; set; }
        public bool Locked { get; set; }
        public string Author_flair_text { get; set; }
        public object[] Treatment_tags { get; set; }
        public bool Visited { get; set; }
        public object Removed_by { get; set; }
        public object Num_reports { get; set; }
        public object Distinguished { get; set; }
        public string Subreddit_id { get; set; }
        public object Mod_reason_by { get; set; }
        public object Removal_reason { get; set; }
        public string Link_flair_background_color { get; set; }
        public string Id { get; set; }
        public bool Is_robot_indexable { get; set; }
        public object Report_reasons { get; set; }
        public string Author { get; set; }
        public object Discussion_type { get; set; }
        public int Num_comments { get; set; }
        public bool Send_replies { get; set; }
        public string Whitelist_status { get; set; }
        public bool Contest_mode { get; set; }
        public object[] Mod_reports { get; set; }
        public bool Author_patreon_flair { get; set; }
        public string Author_flair_text_color { get; set; }
        public string Permalink { get; set; }
        public string Parent_whitelist_status { get; set; }
        public bool Stickied { get; set; }
        public string Url { get; set; }
        public int Subreddit_subscribers { get; set; }
        public float Created_utc { get; set; }
        public int Num_crossposts { get; set; }
        public object Media { get; set; }
        public bool Is_video { get; set; }
        public string Post_hint { get; set; }
        public string Url_overridden_by_dest { get; set; }
        public Preview Preview { get; set; }
        public string Link_flair_template_id { get; set; }
    }
}
